### ISSUE TITLE
push! entry

### ISSUE THREAD

**Issue by rnaldooo** [PGS62/JuliaExcel.jl#13]
im using Clipper when entry push! line return error

`using Clipper`
`polygon = IntPoint[]`
`push!(polygon, IntPoint(348,257))`

┌ Error: Result of type Vector{IntPoint} could not be encoded for return to Excel.
└ @ JuliaExcel C:\Users\reinaldo\.julia\packages\JuliaExcel\Y1cgX\src\JuliaExcel.jl:148

**Comment by PGS62** [comment]
I think your best bet will be to write a method that can convert a `Vector{IntPoint}` into a (say) a `Matrix{Int64}` and make use of that. How about:
`to2d(p) = hcat([p[i].X for i in 1:length(p)],[p[i].Y for i in 1:length(p)])`

![image](https://user-images.githubusercontent.com/18028484/205453020-d2ef9702-d1da-44fd-a1d6-7b27c32b323c.png)

**Comment by PGS62** [comment]
The problem is that your call to `push!` returns a `Vector{IntPoint}` and the relevant function of JuliaExcel (namely `encode_for_xl`) does not know how to encode that for display in an Excel worksheet. So a solution would be to add a method to `encode_for_xl` that handles `Vector{IntPoint}`, by converting the input to `Matrix{Int64}` and encoding that.


This code achieves that:
```
import JuliaExcel.encode_for_xl
encode_for_xl(p::Vector{IntPoint}) = encode_for_xl(hcat([p[i].X for i in eachindex(p)],[p[i].Y for i in eachindex(p)]))

```

![image](https://user-images.githubusercontent.com/18028484/205490164-1a11c544-2197-4d2f-af2c-10cceb5c3e6b.png)
